# Generated by Django 3.1.7 on 2021-03-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=50)),
                ('sets', models.PositiveIntegerField(max_length=50)),
                ('reps', models.PositiveIntegerField(max_length=50)),
                ('weight', models.PositiveIntegerField(max_length=50)),
                ('workout_type', models.CharField(choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Legs', 'Legs')], max_length=20)),
                ('workout_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
